services:
  edge-log-forwarder:
    image: quay.io/mongodb/edge-log-forwarder:v0.23.1
    depends_on:
      - mongodb_container
      - replSetInit
    links:
      - mongodb_container
    volumes:
      - edge_logs:/home/edge_logs
    environment:
      CLIENT_APP_ID: edge-server-04-24-dayzqfg
      CLOUD_BASE_URL: https://services.cloud.mongodb.com
      EDGE_API_KEY: BC0pVjCTUTMQTV1bfN6mKJetbhsGxl7gaCe1iFgnui6TNMrzxGlpZ5I6K8SWPD4V
    restart: unless-stopped
    networks:
      - default
      - internal
  mongodb_container:
    command:
      - --replSet
      - rs0
    image: mongodb/mongodb-enterprise-server:7.0.8-ubi8
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
    networks:
      - internal
  replSetInit:
    command:
      - /bin/sh
      - -c
      - 'mongosh mongodb://mongodb_container:27017 --eval ''rs.isMaster().ismaster || rs.initiate({"_id": "rs0","members" : [{ "_id" : 0, "host" : "mongodb_container:27017" } ] })'''
    image: mongodb/mongodb-enterprise-server:7.0.8-ubi8
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
    restart: on-failure
    networks:
      - internal
  sync_server:
    image: quay.io/mongodb/edge-server:v0.23.1
    depends_on:
      - mongodb_container
      - replSetInit
    links:
      - mongodb_container
    volumes:
      - edge_logs:/app/edge_logs
    environment:
      APP_ID: edge-server-04-24-dayzqfg
      CLOUD_BASE_URL: https://services.cloud.mongodb.com
      DISABLE_LOCAL_UI: "false"
      EDGE_API_KEY: BC0pVjCTUTMQTV1bfN6mKJetbhsGxl7gaCe1iFgnui6TNMrzxGlpZ5I6K8SWPD4V
      EDGE_DISABLE_AUTH: "false"
      EDGE_HTTP_PORT: "80"
      EDGE_QUERY: "*"
      EDGE_WIREPROTOCOL_PORT: "27021"
      MONGO_URI: mongodb://mongodb_container:27017
    ports:
      - 80:80
      - 27021:27021
    restart: unless-stopped
    networks:
      - default
      - internal
volumes:
  edge_logs: {}
  mongodb_data_container: {}
networks:
  default:
    internal: false
  internal:
    internal: true
