name: Check Manifest

on: pull_request

jobs:
  validate:
    name: Validate JSON
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: OrRosenblatt/validate-json-action@0.1.0
        env:
          INPUT_SCHEMA: manifest.schema.json
          INPUT_JSONS: manifest.json
