name: Check Manifest

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Validate Manifest
        working-directory: tools/validate-manifest
        run: |
          npm ci
          npm run build
          npm run test
          npm run validate ../../manifest.json
