name: Push Artifact - SwiftUI

on:
  push:
    branches:
      - main
    paths:
      - "swiftui/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/push-to-artifact-repos
        with:
          source: ./swiftui
          target_repo: mongodb/template-app-swiftui-todo.git
