name: Push Artifact - Web JS (GraphQL)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "other/web-js/generated/prod-graphql/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/push-to-artifact-repo
        with:
          source: ./other/web-js/generated/prod-graphql
          destination_repo: mongodb/template-app-web-graphql-todo.git
          access_token: ${{ secrets.ARTIFACT_REPO_ACCESS_TOKEN }}
